### ISSUE TITLE
Texts are not getting erased

### ISSUE THREAD

**Issue by hiteshsahu** [adamjking3/react-typing-animation#28]
See here

https://codesandbox.io/s/k54yp599oo

**Comment by titchimoto** [comment]
Agreed. Any updates on this? Love the library but this is preventing me from using it in a project.

**Comment by adamjking3** [comment]
Okay, this makes sense. When I originally created the library, I hadn't considered using the `<Reset />` component without setting the `loop` prop on the parent Typing component. However, it is a valid use case. 

It's been a while since I really dived into this codebase, but iirc, the problem is most likely coming from the fact that we render all of the children of the parent Typing component after the entire animation is complete, if the `loop` prop is false.

To fix this, we should instead render the currently typed text at the end of the animation, as this should be set to [] after a Reset.

**Comment by adamjking3** [comment]
Thanks to @dallin-christensen for submitting a PR that fixes this bug!
